### ISSUE TITLE
Polygon grid features shifting with --coalesce-fraction-as-needed

### ISSUE THREAD

**Issue by wisesselo** [felt/tippecanoe#151]
I'm trying to coalesce a grid of hexagons. My issue is that some of the coalesced polygons are shifting vertically. I confirmed this by checking feature ids before and after coalescing. I read in the docs that "the polygons to which nested polygons are coalesced may not necessarily be the immediately enclosing features." I'm not sure if this is what I'm observing, or if there is a way to control this. Any help is appreciated!

This is the command that resulted in the screenshots below:
tippecanoe -o file.mbtiles filenotnull.json --force --maximum-zoom=8 --coalesce-fraction-as-needed

Other things I tried:
--include=_solar_1_mean
--accumulate-attribute=_solar_1_mean:mean
--accumulate-attribute=_solar_1_mean:max

Last zoom level before coalescing occurs:
![z1](https://github.com/felt/tippecanoe/assets/130391961/32cc6b44-82f5-4e98-abc1-88e7004190b9)
First zoom level where coalescing occurs:
![z2](https://github.com/felt/tippecanoe/assets/130391961/4a5cf4c5-4dd4-4f97-bce6-d7c13af5348f)
Further zoomed out:
![z3](https://github.com/felt/tippecanoe/assets/130391961/804a1bba-1c42-468f-8a04-61b9e56dcff2)

**Comment by e-n-f** [comment]
Thanks for the report. The `--coalesce-fraction-as-needed` coalescing coalesces features by quadkey or Hilbert curve adjacency rather than actual two-dimensional adjacency, which I think probably explains the problem you are seeing. Please try the `--hilbert` option, which should generally be a better approximation to actual adjacency. If that isn't enough, I can try to look into how to improve it further.

**Comment by wisesselo** [comment]
Thank you. Using --hilbert improves it significantly for my use case. Here is a before and after:
![hilbert3](https://github.com/felt/tippecanoe/assets/130391961/de271f5e-28fd-4118-8c0e-138c71165abc)
