### ISSUE TITLE
Feasibility of adding geoparquet support 

### ISSUE THREAD

**Issue by mtravis** [felt/tippecanoe#193]
Do we think there's a possibility that geoparquet support will be added at some point? 

We're currently taking the Overture data and converting to flatgeobuf to use with tippecanoe like so. 

``` bash
for file in $filelist
do
    aws s3 cp --no-sign-request $location$file .
    time duckdb -c "install spatial; load spatial; COPY (SELECT id, st_geomfromwkb(geometry) as geom from read_parquet('$file') )  to '$file.fgb' WITH (FORMAT GDAL, DRIVER 'flatgeobuf');"
    rm $file;
done
```

Being able to drop this step would be great. Happy to look at ways at funding the development of this feature if it is possible.

**Comment by bdon** [comment]
What about streaming GeoJSONSeq out of DuckDB and into tippecanoe? 

GeoParquet would entail adding Arrow + Parquet which would complicate the build significantly.

**Comment by mtravis** [comment]
@bdon we're taking the global coverage and converting to fgb. Streaming via GeoJsonSeq would take even longer wouldn't it.

**Comment by bdon** [comment]
I am suggesting using `gpq` so that the GeoJsonSeq never touches disk, like this:

```
gpq convert Cairo_Governorate.parquet --to=geojson | tippecanoe Cairo.geojson -o Cairo.pmtiles
```

It might be faster overall then the intermediate step of writing out fgb to disk, then reading that, unless you are already streaming fgb.

**Comment by mtravis** [comment]
@bdon thanks for the suggestion, streaming to tippecanoe via gpq is not something I had thought about. 

The code snippet I provided probably paints a false picture of what we are actually doing. Currently I'm downloading the entire global dataset of Overture buildings and then converting to Flatgeobufs. I then run something like this

`tippecanoe -overture-buildings -l buildings *.fgb`

That's perfect for what we need. Removing the middle step would be good but it doesn't take a overly long time. If adding Geoparquet support would over complicate the build then I'll close this one for now.

**Comment by ianthetechie** [comment]
Sorry to necro an issue here, but wanted to write down a few things in case it's helpful for other people who stumble across this. I have a similar motivating use case involving planet-scale data, though mine involves routing graphs derived from OSM.

@bdon's suggestion to pipe GeoJSON into tippecanoe _does_ work, but there is a performance penalty. Your GeoJSON producer will far outpace Tippecanoe's ability to read it. Additionally, it seems that if you use tippecanoe's parallel GeoJSON read option (on files; this doesn't work on streams, obviously), it's able to make some other optimizations. All told, the process was several *times* faster for a dataset involving the state of Florida.

FGB as an intermediate step could work, but here are the mains reasons I wanted to avoid something like that for our use case:

* FGB is a super efficient format to consume, but much more involved to produce.  GeoParquet is great because it's also fast to write.
* It involves even more disk space since you have to convert to another format, OR you need to have enough RAM to generate your FGBs there (which could probably work actually.... might try that and see if it's any better).
* Running tippecanoe with a glob of FGBs seems to sacrifice a lot of flexibility. I couldn't figure out how you'd do things like layer and minzoom specification in the dataset directly like you can for GeoJSON. (Our use case involves bringing in different road classifications at different levels; tiles wouldn't be usable without such pruning. If this is possible with FGB, I couldn't find any documentation of it.)

Finally, I want to point out something that isn't necessarily obvious: tippecanoe is quite light on RAM usage, and you might be deceived by this initially when piping in a massive dataset that you've converted to GeoJSON. While you don't need any disk space for massive GeoJSON temp files, you DO need a non-trivial amount of disk space for tippecanoe's caches and temp files. I could not find any documentation of rules of thumb for how much to expect and don't really know the internals myself, but keep that in mind.

Probably the optimal solution today (if you need a lot of flexibility with layers and feature pruning within the layer) is to use a nice filesystem like ZFS and write out GeoJSON first.

If support is ever considered for GeoParquet in the future, it would be nice to keep the record-level metadata (magic column names maybe for maximal compression?) to get those tippecanoe extensions like layer and zoom. I suspect that such an implementation using GeoParquet directly from the filesystem would also be able to take advantage of parquet statistics, which would lead to greater disk efficiency, but I may be off there.
