### ISSUE TITLE
Follow TileJSON spec for metadata table

### ISSUE THREAD

**Issue by rubenpoppe** [felt/tippecanoe#53]
In #44 a model for the metadata table was added, but `vector_layers` is part of the `json` row. Is there a specific reason for this? [The 3.0 TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0) defines `vector_layers` to be a top level field. And in none of the other versions the `json` field is a thing. The [mbtiles tilelive](https://github.com/mapbox/node-mbtiles/blob/master/lib/mbtiles.js#L278) seems to acknowledge this and transforms the data.

**Comment by bdon** [comment]
`vector_layers` as part of the `json` key is part of the MBTiles spec. https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#vector_layers

Any program that presents TileJSON based on MBTiles needs to transform the `metadata` table slightly. The data structure for Tippecanoe follows MBTiles because that's what the existing MBTiles and dirtiles expect, and how the test suite is organized. Is there a specific use case where the internal data model needs to be different?

**Comment by rubenpoppe** [comment]
Oh, I see. I was just wondering why it was that way. Thanks for clearing it up!

**Comment by reyemtm** [comment]
bringing this back up - the use case is - run tippecanoe, and in the case of output to a directory - create a tilejson which has the tiles end point, bounds, min and max zoom, such that you can add the data to a map using `data: "https://.../tilejson.json"` instead of manually setting the tiles, bounds, min and max zoom. You might need one additional cli option to set the root url, not sure.
